baseURL = "https://oconnor0.github.io/fourth-world-srd/"
languageCode = "en-us"
title = "Fourth World SRD"
theme = "kraiklyn"

[params]
sidebarColor = "default"

# [[menu.shortcuts]]
# name = "Kraiklyn on Github"
# url = "https://github.com/jsnjack/kraiklyn"
# weight = 10

[blackfriday]
fractions = false
